name = input("Enter your name: ")
surname= input("Enter your surname: ")
age= input("Enter your age: ")
number1= input("Enter your number1: ")
number2= input("Enter your number2: ")
print(type(name))
print(type(surname))
print(type(age))
print(type(number1))
print(type(number2))

number1= input("Enter your number1: ")
number2= input("Enter your number2: ")
print(int(number1) + int(number2))
print(number1 + number2)