name= "Teodore"
surname= "Ratiani"
Age= 15
school= "64 public school"
academy= "GOA"
favorite_subjects= "Math and Physics"
list="Apple, Samsung, Google pixel, Lenovo, Oneplus"
apple="The iPhone is a line of smartphones developed and marketed by Apple that use the company's own iOS mobile operating system. The first-generation iPhone was announced by then–Apple CEO Steve Jobs on January 9, 2007. Since then, Apple has annually released new iPhone models and iOS versions. As of January 1, 2024, more than 2.3 billion iPhones have been sold, making Apple the largest vendor of mobile phones in 2023."
Samsung="amsung Galaxy (Korean: 삼성 갤럭시; stylized as SΛMSUNG Galaxy since 2015 (except Japan where it omitted the Samsung branding up until 2023),[2] previously stylized as Samsung GALAXY; abbreviated as SG) is a series of computing and Android mobile computing devices that are designed, manufactured and marketed by Samsung Electronics since 29 June 2009. The product line includes the Samsung Galaxy S series of high-end phones, Galaxy Z series of high-end foldables, Galaxy A series, Galaxy F series and Galaxy M series of mid-range phones, the Galaxy Book of laptops, the Samsung Galaxy Tab series, the Samsung Galaxy Watch, the Galaxy Buds series and the Galaxy Fit, and the now historical Galaxy Note series of pioneering phablets."
print("Hello everyone!")
google_pixel="oogle Pixel is a brand of portable consumer electronic devices developed by Google that run either ChromeOS or the Pixel version of the Android operating system. The main line of Pixel products consist of Android-powered smartphones, which have been produced since October 2016 as the replacement of the older Nexus, and of which the Pixel 9, Pixel 9 Pro and Pixel 9 Pro XL are the current models. The Pixel brand also includes laptop and tablet computers, as well as several accessories, and was originally introduced in February 2013 with the Chromebook Pixel."
Lenovo="Lenovo smartphones are marketed as the LePhone in mainland China and the IdeaPhone overseas are smartphones designed and manufactured by the Motorola Mobility, ZUK Mobile and Medion, divisions of Lenovo. On April 27, 2017, Lenovo announced that the ZUK brand would cease operations.[1][2] In 2015, Lenovo subsumed its own smartphone division into the acquired Motorola brand.[3]"
oneplus="OnePlus Technology (Shenzhen) Co., Ltd. (Chinese: 一加科技; pinyin: Yījiā Kējì), doing business as OnePlus, is a Chinese consumer electronics manufacturer headquartered in Shenzhen, Guangdong, China.[7] It was a subsidiary of BBK Electronics, a company which also had Oppo. OnePlus releases three lines of smartphones: its flagship OnePlus line, mid-range Ace line, which is exclusive for the Chinese market, and its budget-oriented Nord line. Both lines are equipped with an Android-based operating system known as OxygenOS or ColorOS."
print("My names is " + name + " " + surname +".")
print("I am " + str(Age) + " years old.")
print("I go to" + " " + school + ".")
print("My favorite subjects are " + favorite_subjects + ".")
print("I also study at the best academy " + academy + ".")
print("Today i will talk about biggest companies in phone industry.")
print("These are:" + list + ".")
print(apple)
print(Samsung)
print(google_pixel)
print(oneplus)
print(Lenovo)
print("Now lets talk about Consoles")
list2="Playstation, Xbox and Nintendo."
print("There are many consoles , but the most known are:"+ list2)
playstation="PlayStation (Japanese: プレイステーション, Hepburn: Pureisutēshon, officially abbreviated as PS) is a video gaming brand that consists of five home video game consoles, two handhelds, a media center, and a smartphone, as well as an online service and multiple magazines. The brand is produced by Sony Interactive Entertainment, a division of Sony. The first PlayStation console was released in Japan in December 1994, and worldwide the following year.[1] The original console in the series was the first console of any type to ship over 100 million units, doing so in under a decade.[2] Its successor, the PlayStation 2, was released in 2000; it is the best-selling home console to date, having reached over 155 million units sold by the end of 2012.[3] Sony's next console, the PlayStation 3, was released in 2006, selling over 87.4 million units by March 2017.[4] Sony's next console, the PlayStation 4, was released in 2013, selling a million units within a day, becoming the fastest selling console in history.[5] The latest console in the series, the PlayStation 5, was released in 2020[6] and sold 10 million units in its first 249 days, unseating its predecessor as the fastest-selling PlayStation console to-date.[7] The main series of controllers utilized by the PlayStation series is the DualShock, a line of vibration-feedback gamepads that sold 28 million units by June 2008.[8]"
xbox="Xbox is a video gaming brand that consists of five home video game consoles, as well as applications (games), streaming service Xbox Cloud Gaming, and online services such as the Xbox network and Xbox Game Pass. The brand is produced by Microsoft Gaming, a division of Microsoft. The brand was first introduced in the United States in November 2001, with the launch of the original Xbox console. The Xbox branding was formerly, from 2012 to 2015, used as Microsoft's digital media entertainment brand replacing Zune.[1][2] In 2022, Microsoft expanded its gaming business and reorganized Xbox to become part of its newly formed Microsoft Gaming division. Under Microsoft Gaming, Xbox's first-party publishers are Xbox Game Studios, ZeniMax Media (Bethesda Softworks), and Activision Blizzard (Activision, Blizzard Entertainment, and King), who own numerous studios and successful franchises. The original device was the first video game console offered by an American company after the Atari Jaguar stopped sales in 1996. It reached over 24 million units sold by May 2006.[3] Microsoft's second console, the Xbox 360, was released in 2005 and has sold 86 million units as of October 2021. The third console, the Xbox One, was released in November 2013 and has sold 58 million units.[4] The fourth line of Xbox consoles, the Xbox Series X and Series S, were released in November 2020. The head of Xbox is Phil Spencer, who succeeded former head Marc Whitten in late March 2014.[5][6]"
nintendo="Nintendo Co., Ltd.[b] is a Japanese multinational video game company headquartered in Kyoto. It develops, publishes and releases both video games and video game consoles. Nintendo was founded in 1889 as Nintendo Koppai[c] by craftsman Fusajiro Yamauchi and originally produced handmade hanafuda playing cards. After venturing into various lines of business during the 1960s and acquiring a legal status as a public company, Nintendo distributed its first console, the Color TV-Game, in 1977. It gained international recognition with the release of Donkey Kong in 1981 and the Nintendo Entertainment System and Super Mario Bros. in 1985. Since then, Nintendo has produced some of the most successful consoles in the video game industry, such as the Game Boy, the Super Nintendo Entertainment System, the Nintendo DS, the Wii, and the Nintendo Switch. It has created or published numerous major franchises, including Mario, Donkey Kong, The Legend of Zelda, Metroid, Fire Emblem, Kirby, Star Fox, Pokémon, Super Smash Bros., Animal Crossing, Pikmin, Xenoblade Chronicles, and Splatoon, and Nintendo's mascot, Mario, is internationally recognized, as well as other characters like Donkey Kong, Link, Samus Aran, Kirby, and Pikachu. The company has sold more than 5.592 billion video games and over 836 million hardware units globally, as of March 2023. Nintendo has multiple subsidiaries in Japan and abroad, in addition to business partners such as HAL Laboratory, Intelligent Systems, Game Freak, and The Pokémon Company. Nintendo and its staff have received awards including Emmy Awards for Technology & Engineering, Game Awards, Game Developers Choice Awards, and British Academy Games Awards. It is one of the wealthiest and most valuable companies in the Japanese market."
print(playstation)
print(xbox)
print(nintendo)
print("Thats all i wanted to talk about.")
print("Thank you for reading this.")
print("Goodbye.")